### ISSUE TITLE
unittests fail on php5.6

### ISSUE THREAD

**Issue by mjrider** [poef/arc-prototype#3]
1) PrototypeTest::testPrototypeInheritance
Cannot bind an instance to a static closure

/home/muller/git/arc/arc-prototype/src/prototype.php:213
/home/muller/git/arc/arc-prototype/src/prototype.php:238
/home/muller/git/arc/arc-prototype/tests/PrototypeTest.php:41

FAILURES!
Tests: 10, Assertions: 18, Errors: 1.

**Comment by poef** [comment]
No longer an issue, php 7 works fine, php5 is no longer supported :)
